### ISSUE TITLE
Update Spring Boot version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-rest-hateoas#32]
Updating the Spring Boot version is a constantly ongoing task, and it's easy to do. That makes it a good spot for beginners to get started by making a PR.

To change the Spring Boot version, you must change it in the following files:

complete/build.gradle
complete/pom.xml
initial/build.gradle
initial/pom.xml

**Comment by NizarBenalla** [comment]
can I work on this?

**Comment by Buzzardo** [comment]
> can I work on this?

Definitely. In open source, anyone can work on anything. That's the point. However, not everyone can approve everything. So, someone makes a pull request (PR) and the repository owners check whether it makes sense and, if it does make sense, approve that PR.

So, in this case, do the work in a local branch and then make a pull request to this repository. If you did the right thing, we'll approve it, and you will have committed to a Spring repository. How to make a local branch and a PR is covered in all kinds of places out there on the Internet.

Sorry if you already know all that. We have to write for novices even when people might be experts, because we rarely know for sure.

**Comment by robertmcnees** [comment]
Closing this as it will be managed on a different level.
