### ISSUE TITLE
methodOn is undefined

### ISSUE THREAD

**Issue by leonardoblanco** [spring-guides/gs-rest-hateoas#8]
With these codes the "methodOn" is undefined. I need to add the import static to compile:

import static org.springframework.hateoas.mvc.ControllerLinkBuilder.methodOn;

This is normal?

Thanks!

**Comment by gregturn** [comment]
There is already a static import in the complete copy.

**Comment by rafa-maciel** [comment]
An import needs to be settled and it has been update.

import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.*;

**Comment by shashankSkydale** [comment]
Thanks Rafa for providing the correct answer.
